[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build && cd ../netlify/functions && npm install"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200