import { createContext, useContext, useState } from 'react';

export const TRACK_IDS = ['software', 'teaching', 'data'];

export const TRACKS = {
  software: {
    id: 'software',
    label: 'Software Engineer',
    portfolioStatement: 'You are viewing my Software Engineer portfolio',
    color: '#2D6BE4',
    accentBg: '#EEF4FF',
    accentBorder: '#BFD3FF',
    heroRoles: ['Full-Stack Developer', 'React Engineer', 'Backend Developer', 'MBA Candidate'],
    heroTagline: 'I build fast, scalable web applications.',
    bio: `Full-stack software developer and MBA candidate at Missouri State University. Over the past 3 years I have shipped production web applications with React, Node.js, and MySQL — including a crowdfunding platform, a portfolio generator, and an e-commerce shop. Before returning to school I spent 18 months as a Health Actuarial Technician at Aon, where I built rigorous analytical habits across 100+ medical plan datasets. My Actuarial Mathematics background gives me an analytical edge most developers don't have. Based in Springfield, MO and open to remote or in-person software engineering roles.`,
    highlights: [
      { value: '3+',  label: 'Years Building'  },
      { value: '3+',  label: 'Projects Shipped' },
      { value: '10+', label: 'Technologies'     },
    ],
    skills: [
      {
        name: 'Frontend Development',
        icon: 'FaReact',
        level: 'Advanced',
        desc: '3 years of professional experience building production React applications. I work from Figma designs, manage state with Redux Toolkit, and ship responsive UIs with Tailwind CSS and Bootstrap.',
      },
      {
        name: 'Backend Development',
        icon: 'FaNodeJs',
        level: 'Advanced',
        desc: 'Built REST APIs with Node.js and Express in production. Authentication systems, Paystack payment processing, Nodemailer email flows, and database-backed business logic across multiple live applications.',
      },
      {
        name: 'Database Design',
        icon: 'FaDatabase',
        level: 'Advanced',
        desc: 'Professional experience with MySQL and MongoDB. Designed normalized schemas for a crowdfunding platform and portfolio generator, with a focus on data integrity and financial transaction correctness.',
      },
      {
        name: 'Secure Authentication',
        icon: 'FaShieldAlt',
        level: 'Advanced',
        desc: 'Implemented JWT-based authentication, bcrypt password hashing, and role-based access control in production applications. Also handled payment webhook verification for financial security.',
      },
      {
        name: 'Analytical Problem Solving',
        icon: 'FaLightbulb',
        level: 'Advanced',
        desc: 'B.S. in Actuarial Mathematics and 18 months at Aon give me a rigorous analytical foundation. I approach engineering problems with the same precision I applied to financial modeling and risk analysis.',
      },
      {
        name: 'Version Control',
        icon: 'FaGitAlt',
        level: 'Experienced',
        desc: '3 years using Git in professional team environments. Familiar with branching strategies, pull request workflows, and collaborative code review practices.',
      },
      {
        name: 'Responsive Design',
        icon: 'FaMobileAlt',
        level: 'Experienced',
        desc: 'Mobile-first with Tailwind CSS and Bootstrap across every application I have built. I test on multiple viewport sizes and treat responsive design as a baseline requirement, not an afterthought.',
      },
      {
        name: 'Business and Product Thinking',
        icon: 'FaCogs',
        level: 'Intermediate',
        desc: 'MBA candidate with prior experience translating business requirements into technical implementations at Techvibes. I understand why the software matters, not just how it works.',
      },
    ],
    stack: ['React JS', 'Node.js', 'Express', 'Redux', 'MySQL', 'MongoDB', 'Tailwind CSS', 'JavaScript', 'HTML5', 'CSS3', 'Git', 'GitHub', 'Material UI', 'Bootstrap', 'Figma', 'Vite'],
    projectIds: [1, 4, 5],
    experience: [
      {
        id: 'exp-swe-1',
        role: 'Junior Software Developer',
        company: 'Techvibes International Limited',
        companyUrl: 'https://techvibes.africa',
        logo: 'techvibes',
        location: 'Abuja, Nigeria (Remote)',
        period: 'Jan 2024 – Dec 2024',
        type: 'Full-time',
        description: 'Engineered and shipped full-stack features across production applications, building React components from Figma designs and integrating third-party APIs to deliver real-time user experiences.',
        bullets: [
          'Engineered and shipped full-stack features across production applications, building React components directly from Figma designs to deliver seamless user experiences.',
          'Developed Node.js backend modules covering user authentication, input validation, payment processing, and automated email workflows, reducing manual intervention in critical transaction flows.',
          'Drove cross-functional collaboration between design, product, and engineering teams to convert business requirements into well-tested, maintainable code.',
        ],
      },
      {
        id: 'exp-swe-2',
        role: 'Software Developer Intern',
        company: 'Techvibes International Limited',
        companyUrl: 'https://techvibes.africa',
        logo: 'techvibes',
        location: 'Abuja, Nigeria (Remote)',
        period: 'Mar 2022 – Aug 2022',
        type: 'Internship',
        description: 'Delivered responsive web interfaces and supported backend development in a live production environment.',
        bullets: [
          'Delivered responsive, accessible web interfaces using HTML, CSS, JavaScript, and React, contributing to live products used by real users.',
          'Supported backend development in Node.js and MySQL, gaining hands-on experience with authentication flows, database queries, and API integration.',
        ],
      },
      {
        id: 'exp-swe-3',
        role: 'Graduate Assistant, Finance and Risk Management',
        company: 'Missouri State University',
        companyUrl: 'https://www.missouristate.edu',
        logo: 'msu',
        location: 'Springfield, MO',
        period: 'Aug 2025 – Present',
        type: 'Part-time',
        description: 'Assisting faculty in the Finance and Risk Management department while pursuing the MBA.',
        bullets: [
          'Communicate complex quantitative concepts clearly to diverse undergraduate audiences, demonstrating technical communication skills essential in collaborative engineering environments.',
          'Reinforce applied knowledge in finance, economics, and risk management through structured support and tutoring.',
        ],
      },
    ],
    education: [
      {
        id: 'edu-swe-1',
        degree: 'Master of Business Administration (MBA)',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Aug 2025 – Expected May 2027',
        gpa: 'In Progress',
        courses: ['Finance', 'Risk Management', 'Business Analytics', 'Strategy'],
      },
      {
        id: 'edu-swe-2',
        degree: 'B.S. Actuarial Mathematics (Minor: Computer Science)',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Aug 2019 – May 2023',
        gpa: "Dean's List (7 semesters)",
        courses: ['Algorithms & Complexity Analysis', 'Theory of Computing', 'Object-Oriented Programming', 'Structured Programming'],
      },
    ],
    interests: [
      { icon: 'FaSitemap',   label: 'System Design',     desc: 'Thinking about how large-scale systems are architected, how services communicate, and what makes some systems remarkably resilient at scale.' },
      { icon: 'FaRobot',     label: 'AI and ML',          desc: 'Exploring how machine learning models are trained and deployed. Genuinely curious about where AI adds real value in software products versus where it is overhyped.' },
      { icon: 'FaChartLine', label: 'Data and Analytics', desc: 'Bringing an actuarial lens to data problems. Precision, reproducibility, and what the numbers actually tell you versus what people assume.' },
      { icon: 'FaFutbol',    label: 'Football',           desc: 'Lifelong football fan. I follow matches closely and find the tactical and analytics dimensions of the sport increasingly interesting.' },
      { icon: 'FaGamepad',   label: 'Gaming',             desc: 'Strategy games that challenge pattern recognition, resource management, and thinking under constraint.' },
      { icon: 'FaGlobe',     label: 'Business Strategy',  desc: 'How business decisions connect to technical ones. The MBA gives me a different lens on the software I build and why it matters.' },
    ],
    services: [
      {
        icon: 'FaCode',
        title: 'Web Application Development',
        desc: 'Full-stack applications built with React and Node.js. From user authentication and payment processing to real-time features, I build complete, production-ready systems.',
        deliverables: ['React frontend', 'Node.js and Express backend', 'Database design (MySQL or MongoDB)', 'Authentication and user management', 'Deployment ready'],
      },
      {
        icon: 'FaShoppingCart',
        title: 'E-Commerce Solutions',
        desc: 'Online shops with secure checkout, product management, and order tracking. I have integrated Paystack for live payment processing in real production applications.',
        deliverables: ['Product catalogue and cart', 'Paystack payment integration', 'Order management', 'User accounts and profiles', 'Automated email receipts'],
      },
      {
        icon: 'FaGlobe',
        title: 'Business Websites and Landing Pages',
        desc: 'Professional websites that represent your business clearly and convert visitors into customers. Fully responsive, fast, and built with search visibility in mind.',
        deliverables: ['Custom responsive design', 'Contact and inquiry forms', 'SEO fundamentals', 'Fast load times', 'Mobile-first layout'],
      },
      {
        icon: 'FaUserCircle',
        title: 'Portfolio and Personal Websites',
        desc: 'Personal sites that present your work, skills, and story in a way that gets attention. I know what makes a portfolio stand out because I have built one from scratch.',
        deliverables: ['Multi-section custom layout', 'Project showcases', 'Animated and interactive UI', 'Contact form with email integration', 'Responsive across all devices'],
      },
      {
        icon: 'FaServer',
        title: 'Backend API Development',
        desc: 'Clean, secure REST APIs built with Node.js and Express. Covers authentication, data validation, file uploads, email flows, and third-party service integrations.',
        deliverables: ['REST API design', 'JWT authentication', 'Database integration', 'Webhook and event handling', 'Third-party API integrations'],
      },
      {
        icon: 'FaDatabase',
        title: 'Database Design and Optimization',
        desc: 'Normalized relational database schemas and optimized SQL queries. Based on production experience with MySQL and MongoDB across financial and user-facing systems.',
        deliverables: ['Schema and data model design', 'SQL query optimization', 'Data normalization', 'MySQL and MongoDB', 'Migration support'],
      },
    ],
    cvFile: '/Simon_Lotigo_Software_CV (1).docx',
    cvLabel: 'Software Engineer CV',
  },

  teaching: {
    id: 'teaching',
    label: 'Finance & Risk',
    portfolioStatement: 'You are viewing my Finance & Actuarial portfolio',
    color: '#16A34A',
    accentBg: '#EDFAF3',
    accentBorder: '#86EFAC',
    heroRoles: ['Health Actuarial Technician', 'MBA Candidate', 'Risk Analyst', 'Finance Professional'],
    heroTagline: 'I translate data into financial clarity.',
    bio: `MBA candidate at Missouri State University with 18 months of professional actuarial experience at Aon Corporation in Dallas, TX. As a Health Actuarial Technician I performed end-to-end analysis across 100+ medical plan datasets — conducting experience studies, reserve calculations, and trend projections that directly informed financial strategy for ~40 client accounts. My B.S. in Actuarial Mathematics and ongoing MBA give me both quantitative depth and business perspective to navigate complex financial problems. Open to finance, risk, and analytics roles.`,
    highlights: [
      { value: '18mo', label: 'Actuarial Exp.' },
      { value: '100+', label: 'Plans Analyzed'  },
      { value: '60+',  label: 'Client Reports'  },
    ],
    skills: [
      {
        name: 'Actuarial Analysis',
        icon: 'FaChartLine',
        level: 'Experienced',
        desc: '18 months at Aon performing experience studies, reserve calculations, and multi-year trend projections across 100+ medical plan datasets for ~40 client accounts.',
      },
      {
        name: 'Financial Modeling',
        icon: 'FaTable',
        level: 'Experienced',
        desc: 'Built financial models at Aon to evaluate carrier bids, RFPs, and renewal data, modeling plan feasibility and cost impact to guide client plan selection and budget design.',
      },
      {
        name: 'Statistical Reasoning',
        icon: 'MdFunctions',
        level: 'Advanced',
        desc: 'B.S. in Actuarial Mathematics with coursework in Mathematical Probability, Applied Regression, and Risk Analysis. Strong foundation in statistical inference and quantitative modeling.',
      },
      {
        name: 'Risk Assessment',
        icon: 'FaShieldAlt',
        level: 'Experienced',
        desc: 'Quantitative and qualitative risk assessments through actuarial work at Aon and competitive case study experience at Spencer-RIMS, modeling business vulnerabilities and mitigation strategies.',
      },
      {
        name: 'Client Reporting and Presentations',
        icon: 'FaClipboardList',
        level: 'Experienced',
        desc: 'Produced 60+ data-driven client presentations at Aon, translating complex financial findings into clear, executive-ready recommendations that drove real business decisions.',
      },
      {
        name: 'Excel and Structured Data',
        icon: 'FaCogs',
        level: 'Advanced',
        desc: 'Advanced Excel user from actuarial work at Aon: pivot tables, financial models, structured querying, and reporting dashboards used daily in a professional setting.',
      },
      {
        name: 'SQL and Database Querying',
        icon: 'FaDatabase',
        level: 'Intermediate',
        desc: 'Experience with MySQL and MongoDB from professional software development. Applied to managing structured financial data, transaction records, and production reporting pipelines.',
      },
      {
        name: 'Communication of Complex Concepts',
        icon: 'FaUsers',
        level: 'Experienced',
        desc: 'As a GA at MSU and through client-facing actuarial work at Aon, I have consistently translated technical financial and mathematical content into clear communication for varied audiences.',
      },
    ],
    stack: ['Excel', 'Python', 'SQL', 'R', 'MySQL', 'PowerPoint', 'Git', 'GitHub', 'JavaScript', 'React JS', 'Node.js'],
    projectIds: [],
    experience: [
      {
        id: 'exp-fin-1',
        role: 'Health Actuarial Technician',
        company: 'Aon Corporation',
        companyUrl: 'https://www.aon.com',
        logo: 'aon',
        location: 'Dallas, TX',
        period: 'Aug 2023 – Feb 2025',
        type: 'Full-time',
        description: "Performed end-to-end actuarial analysis for ~40 corporate client accounts within Aon's Health Solutions practice.",
        bullets: [
          'Performed end-to-end actuarial analysis on 100+ medical plan datasets, conducting experience studies, reserve calculations, and multi-year trend projections that informed client financial strategy.',
          'Evaluated carrier bids, RFPs, and renewal data to model plan feasibility and cost impact, guiding clients toward optimal plan selection and budget design.',
          'Produced 60+ data-driven client presentations distilling complex financial findings into clear, executive-ready recommendations that drove real business decisions.',
        ],
      },
      {
        id: 'exp-fin-2',
        role: 'Graduate Assistant, Finance and Risk Management',
        company: 'Missouri State University',
        companyUrl: 'https://www.missouristate.edu',
        logo: 'msu',
        location: 'Springfield, MO',
        period: 'Aug 2025 – Present',
        type: 'Part-time',
        description: 'Assisting faculty in the Finance and Risk Management department while pursuing the MBA.',
        bullets: [
          'Assist faculty with data preparation, course material development, and quantitative grading in finance and risk management.',
          'Deliver structured sessions translating abstract mathematical and financial concepts into practical understanding for undergraduate students.',
        ],
      },
    ],
    education: [
      {
        id: 'edu-fin-1',
        degree: 'Master of Business Administration (MBA)',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Aug 2025 – Expected May 2027',
        gpa: 'In Progress',
        courses: ['Finance', 'Risk Management', 'Business Analytics', 'Strategy'],
      },
      {
        id: 'edu-fin-2',
        degree: 'B.S. Actuarial Mathematics (Minor: Computer Science)',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Aug 2019 – May 2023',
        gpa: "Dean's List (7 semesters)",
        courses: ['Mathematical Probability', 'Applied Regression', 'Risk Analysis', 'Financial Modeling'],
      },
    ],
    interests: [
      { icon: 'FaChartLine', label: 'Actuarial Science',  desc: 'The intersection of mathematics, statistics, and financial risk. After working at Aon, I developed deep appreciation for the precision and rigor required in actuarial practice.' },
      { icon: 'FaShieldAlt', label: 'Risk Management',    desc: "Identifying, quantifying, and mitigating risk across complex systems. My Gamma Iota Sigma membership and Spencer-RIMS case study deepened my interest in applied risk management." },
      { icon: 'FaRobot',     label: 'FinTech',            desc: "The convergence of financial expertise and software engineering. My background spans both, and I'm genuinely excited about building technology that addresses real financial problems." },
      { icon: 'FaFutbol',    label: 'Football',           desc: 'Lifelong football fan. I follow matches closely and find the sports analytics angle increasingly interesting as data reshapes how we understand the game.' },
      { icon: 'FaBookOpen',  label: 'Business Strategy',  desc: 'How companies create, capture, and sustain value. The MBA gives me a framework I actively apply to how I think about financial systems and product decisions.' },
      { icon: 'FaGlobe',     label: 'Global Markets',     desc: 'International financial markets, emerging economies, and how risk behaves across different regulatory and economic environments.' },
    ],
    services: [
      {
        icon: 'FaChartLine',
        title: 'Actuarial Analysis and Consulting',
        desc: 'Health plan analysis, experience studies, reserve calculations, and trend projections based on 18 months of professional actuarial experience at Aon.',
        deliverables: ['Experience studies', 'Reserve calculations', 'Trend projections', 'Plan feasibility modeling', 'Client reporting'],
      },
      {
        icon: 'FaTable',
        title: 'Financial Modeling and Reporting',
        desc: 'Structured financial models for decision-making. Carrier bid evaluation, RFP analysis, cost modeling, and executive presentations grounded in actuarial rigor.',
        deliverables: ['Financial models', 'Carrier bid and RFP evaluation', 'Cost impact analysis', 'Executive presentations', 'Budget design support'],
      },
      {
        icon: 'FaDatabase',
        title: 'Data Analysis and SQL Reporting',
        desc: 'Structured data analysis using SQL and Excel. Experience with large-scale datasets from actuarial work, combined with software development skills for technical data pipelines.',
        deliverables: ['SQL querying and reporting', 'Excel dashboard development', 'Data cleaning and validation', 'Trend and pattern analysis'],
      },
      {
        icon: 'FaShieldAlt',
        title: 'Risk Assessment and Scenario Modeling',
        desc: 'Quantitative and qualitative risk assessments across business domains. Based on professional actuarial practice and competitive case study experience with Spencer-RIMS.',
        deliverables: ['Risk identification and quantification', 'Scenario and sensitivity modeling', 'Mitigation strategy development', 'Risk presentation and communication'],
      },
      {
        icon: 'FaCode',
        title: 'Finance-Focused Web Applications',
        desc: 'Full-stack web applications built around financial data. Dashboards, reporting tools, and fintech products that pair engineering precision with actuarial rigor.',
        deliverables: ['Financial dashboard development', 'Data visualization tools', 'Backend with financial logic', 'MySQL and MongoDB integration'],
      },
    ],
    cvFile: '/Simon_Lotigo_DataScience_CV.docx',
    cvLabel: 'Finance & Actuarial CV',
  },

  data: {
    id: 'data',
    label: 'Data Science',
    portfolioStatement: 'You are viewing my Data Science portfolio',
    color: '#9333EA',
    accentBg: '#F5F0FF',
    accentBorder: '#D8B4FE',
    heroRoles: ['Data Science Enthusiast', 'Data Analyst', 'Applied Statistician', 'Actuarial Professional'],
    heroTagline: 'I turn numbers into decisions.',
    bio: `Quantitatively trained MBA candidate with actuarial industry experience at Aon and hands-on skills in statistical analysis, financial modeling, SQL, and Python. I spent 18 months as a Health Actuarial Technician at Aon analyzing 100+ medical plan datasets across ~40 client accounts. My B.S. in Actuarial Mathematics and software engineering background give me a rare combination: statistical training, data engineering capability, and business communication skills. Actively developing Python and R alongside strong SQL and analytical foundations. Based in Springfield, MO and open to data science and analytics roles.`,
    highlights: [
      { value: '18mo', label: 'Industry Analytics' },
      { value: '100+', label: 'Datasets Analyzed'  },
      { value: '3+',   label: 'Dev. Experience'    },
    ],
    skills: [
      {
        name: 'Statistical Reasoning',
        icon: 'FaChartLine',
        level: 'Advanced',
        desc: 'B.S. in Actuarial Mathematics with graduate coursework in Mathematical Probability and Applied Regression. Applied statistical inference, trend projections, and reserve calculations professionally at Aon.',
      },
      {
        name: 'Actuarial Analysis',
        icon: 'FaShieldAlt',
        level: 'Experienced',
        desc: '18 months at Aon performing experience studies and reserve calculations across 100+ medical plan datasets. Professional-grade exposure to how statistical modeling drives real financial decisions.',
      },
      {
        name: 'Python',
        icon: 'SiPython',
        level: 'Beginner',
        desc: 'Actively developing Python for data analysis and scripting. Building proficiency in pandas, NumPy, and matplotlib to complement my statistical and SQL foundations.',
      },
      {
        name: 'SQL and Database Querying',
        icon: 'FaDatabase',
        level: 'Advanced',
        desc: '3 years of production experience with MySQL and MongoDB from professional software development. Skilled at writing queries, designing schemas, and ensuring data consistency in live systems.',
      },
      {
        name: 'Excel and Financial Data',
        icon: 'FaTable',
        level: 'Advanced',
        desc: 'Advanced Excel user from actuarial work at Aon: pivot tables, financial models, structured querying, and reporting dashboards. Moving from spreadsheet workflows into Python-based pipelines.',
      },
      {
        name: 'Financial Modeling',
        icon: 'FaCogs',
        level: 'Experienced',
        desc: 'Built financial models at Aon evaluating carrier bids, RFPs, and renewal data. Experience modeling plan feasibility, cost impact, and trend projections across complex datasets.',
      },
      {
        name: 'Algorithms and Complexity',
        icon: 'FaStream',
        level: 'Advanced',
        desc: 'Undergraduate coursework in Algorithms and Complexity Analysis. Strong understanding of Big-O notation, common data structures, and how computational cost scales with input size.',
      },
      {
        name: 'R',
        icon: 'FaChartBar',
        level: 'Beginner',
        desc: 'Beginning to use R for statistical analysis in Applied Regression coursework. Motivated and actively developing this skill to complement Python and SQL.',
      },
    ],
    stack: ['Python', 'MySQL', 'MongoDB', 'R', 'SQL', 'Excel', 'JavaScript', 'Git', 'GitHub', 'React JS', 'Node.js', 'Express'],
    projectIds: [1, 5],
    experience: [
      {
        id: 'exp-data-1',
        role: 'Health Actuarial Technician',
        company: 'Aon Corporation',
        companyUrl: 'https://www.aon.com',
        logo: 'aon',
        location: 'Dallas, TX',
        period: 'Aug 2023 – Feb 2025',
        type: 'Full-time',
        description: "Applied quantitative analysis and statistical modeling to health plan data across 40+ corporate client accounts within Aon's Health Solutions practice.",
        bullets: [
          'Performed end-to-end actuarial analysis on 100+ medical plan datasets, conducting experience studies, reserve calculations, and multi-year trend projections that directly informed client financial strategy.',
          'Evaluated carrier bids, RFPs, and renewal data to model plan feasibility and cost impact, applying structured analytical frameworks to guide clients toward optimal plan selection.',
          'Produced 60+ data-driven client presentations distilling complex financial findings into clear, actionable recommendations.',
        ],
      },
      {
        id: 'exp-data-2',
        role: 'Graduate Assistant, Finance and Risk Management',
        company: 'Missouri State University',
        companyUrl: 'https://www.missouristate.edu',
        logo: 'msu',
        location: 'Springfield, MO',
        period: 'Aug 2025 – Present',
        type: 'Part-time',
        description: 'Assisting with data preparation and quantitative coursework in the Finance and Risk Management department while pursuing the MBA.',
        bullets: [
          'Assist faculty with data preparation, course material development, and quantitative grading in finance and risk management.',
          'Deliver structured sessions translating abstract quantitative concepts into practical understanding for undergraduate students.',
        ],
      },
      {
        id: 'exp-data-3',
        role: 'Junior Software Developer',
        company: 'Techvibes International Limited',
        companyUrl: 'https://techvibes.africa',
        logo: 'techvibes',
        location: 'Abuja, Nigeria (Remote)',
        period: 'Jan 2024 – Dec 2024',
        type: 'Full-time',
        description: 'Applied data engineering discipline to production software systems, building SQL-backed data pipelines and enforcing data integrity.',
        bullets: [
          'Built and maintained SQL database schemas for production applications, enforcing data integrity through structured validation logic and transaction-safe backend workflows.',
          'Developed data pipelines connecting users, financial events, and reporting outputs, applying systematic problem-solving to ensure accuracy of monetary records.',
        ],
      },
    ],
    education: [
      {
        id: 'edu-data-1',
        degree: 'Master of Business Administration (MBA)',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Aug 2025 – Expected May 2027',
        gpa: 'In Progress',
        courses: ['Mathematical Probability', 'Applied Regression', 'Finance', 'Business Analytics'],
      },
      {
        id: 'edu-data-2',
        degree: 'B.S. Actuarial Mathematics (Minor: Computer Science)',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Aug 2019 – May 2023',
        gpa: "Dean's List (7 semesters)",
        courses: ['Algorithms & Complexity Analysis', 'Mathematical Probability', 'Applied Regression', 'Risk Analysis'],
      },
    ],
    interests: [
      { icon: 'FaChartLine', label: 'Statistical Modelling', desc: 'Regression models, probability distributions, and applying statistical theory to real-world datasets. Applied at Aon and now the focus of my graduate coursework.' },
      { icon: 'FaShieldAlt', label: 'Actuarial Science',     desc: 'How mathematics and statistics are applied to financial risk. 18 months at Aon gave me professional depth in this space that continues to shape how I think about data.' },
      { icon: 'FaRobot',     label: 'Machine Learning',      desc: 'Supervised and unsupervised learning, model evaluation, and the mathematics behind the algorithms. Actively learning and genuinely excited about this space.' },
      { icon: 'FaFutbol',    label: 'Football',              desc: 'Lifelong football fan and increasingly interested in sports analytics and how data is reshaping how we understand the game.' },
      { icon: 'MdFunctions', label: 'Applied Mathematics',   desc: 'How abstract mathematical structures show up in data science, optimization, and algorithm design. My Actuarial Mathematics background feels increasingly relevant here.' },
      { icon: 'FaBookOpen',  label: 'Continuous Learning',   desc: 'Online courses, research papers, and working through real datasets. Always building toward the next skill on the list.' },
    ],
    services: [
      {
        icon: 'FaDatabase',
        title: 'Database Design and Querying',
        desc: 'Relational database design, normalized schemas, and optimized SQL queries built from 3 years of production experience with MySQL and MongoDB in live applications.',
        deliverables: ['Schema and data model design', 'SQL query optimization', 'Data normalization', 'MySQL and MongoDB', 'Migration and seed support'],
      },
      {
        icon: 'FaChartLine',
        title: 'Data Analysis and Reporting',
        desc: 'Structured analysis of datasets using SQL, Excel, and Python. I extract patterns, validate hypotheses, and translate findings into clear, actionable reports grounded in statistical and actuarial reasoning.',
        deliverables: ['Exploratory data analysis', 'Statistical summaries', 'Data cleaning and validation', 'Written findings and interpretation'],
      },
      {
        icon: 'FaShieldAlt',
        title: 'Actuarial and Financial Data Analysis',
        desc: 'Experience study design, reserve calculations, trend projection modeling, and carrier RFP evaluation — based on 18 months of professional actuarial work at Aon Corporation.',
        deliverables: ['Experience studies', 'Reserve calculations', 'Trend projections', 'Financial plan modeling', 'Executive reporting'],
      },
      {
        icon: 'FaCode',
        title: 'Data-Driven Web Applications',
        desc: 'Full-stack applications where the data layer is central to the product. Dashboards, reporting tools, and systems built so the numbers are always accessible, accurate, and fast.',
        deliverables: ['React frontend with data displays', 'Node.js backend with analytics logic', 'Database integration', 'Charts and visualizations'],
      },
      {
        icon: 'FaCogs',
        title: 'Backend and API Integration',
        desc: 'APIs that serve structured data cleanly to frontends or third-party consumers. Input validation, authentication, and reliable documentation included as standard.',
        deliverables: ['REST API design', 'Data validation and sanitization', 'JWT authentication', 'Third-party API connections', 'Endpoint documentation'],
      },
    ],
    cvFile: '/Simon_Lotigo_DataScience_CV.docx',
    cvLabel: 'Data Science CV',
  },
};

const TrackContext = createContext(null);

export const TrackProvider = ({ children }) => {
  const [activeTrack, setActiveTrack] = useState('software');
  const track = TRACKS[activeTrack];

  return (
    <TrackContext.Provider value={{ activeTrack, setActiveTrack, track, TRACKS }}>
      {children}
    </TrackContext.Provider>
  );
};

export const useTrack = () => useContext(TrackContext);
