export {default as LoginPage } from './auth/Login/Login'
export {default as RegisterPage } from './auth/Register/Register'
export { default as HomePage } from './dashboard/home/Home'
export { default as DashboardProjectPage } from './dashboard/project/Project'
export { default as DashboardCategoryPage } from './dashboard/category/Category'
export { default as DashboardStacksPage } from './dashboard/stack/Stack'
export { default as DashboardProfilePage } from './dashboard/profile/Profile'
export { default as LandingPage } from './public/landing/Landing'
export { default as ProjectPage } from './public/project/Project'
export { default as PricingPage } from './public/pricing/Pricing'
